/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 game.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
    Object_0: THREE.Mesh
    Object_0_1: THREE.Mesh
    Wheel_FL: THREE.Mesh
    Wheel_FR: THREE.Mesh
    Wheel_RL: THREE.Mesh
    Wheel_RR: THREE.Mesh
    rock_main: THREE.Mesh
    tree_main: THREE.Mesh
  }
  materials: {
    ['Material.009']: THREE.MeshPhysicalMaterial
    ['Material.000']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/game.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} />
      <mesh geometry={nodes.rock_main.geometry} material={nodes.rock_main.material} />
      <mesh geometry={nodes.tree_main.geometry} material={nodes.tree_main.material} />
      <mesh geometry={nodes.Object_0.geometry} material={materials['Material.009']} />
      <mesh geometry={nodes.Object_0_1.geometry} material={materials['Material.000']} />
      <mesh geometry={nodes.Wheel_FL.geometry} material={materials['Material.003']} position={[0.836, -0.639, 0.646]} />
      <mesh geometry={nodes.Wheel_FR.geometry} material={materials['Material.003']} position={[0.836, -0.639, -0.646]} />
      <mesh geometry={nodes.Wheel_RL.geometry} material={materials['Material.003']} position={[-0.836, -0.639, 0.646]} />
      <mesh geometry={nodes.Wheel_RR.geometry} material={materials['Material.003']} position={[-0.836, -0.639, -0.646]} />
    </group>
  )
}

useGLTF.preload('/game.glb')
